/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GameRouteImport } from './routes/game'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzleIndexRouteImport } from './routes/puzzle.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PuzzleDateRouteImport } from './routes/puzzle.$date'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AnalyzeClipIdRouteImport } from './routes/analyze.$clipId'
import { Route as ForumTIdRouteImport } from './routes/forum.t.$id'
import { Route as ForumCSlugRouteImport } from './routes/forum.c.$slug'
import { Route as ApiClipSignRouteImport } from './routes/api/clip/sign'
import { Route as ApiClipRenderRouteImport } from './routes/api/clip/render'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleIndexRoute = PuzzleIndexRouteImport.update({
  id: '/puzzle/',
  path: '/puzzle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleDateRoute = PuzzleDateRouteImport.update({
  id: '/puzzle/$date',
  path: '/puzzle/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeClipIdRoute = AnalyzeClipIdRouteImport.update({
  id: '/analyze/$clipId',
  path: '/analyze/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTIdRoute = ForumTIdRouteImport.update({
  id: '/forum/t/$id',
  path: '/forum/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCSlugRoute = ForumCSlugRouteImport.update({
  id: '/forum/c/$slug',
  path: '/forum/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClipSignRoute = ApiClipSignRouteImport.update({
  id: '/api/clip/sign',
  path: '/api/clip/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClipRenderRoute = ApiClipRenderRouteImport.update({
  id: '/api/clip/render',
  path: '/api/clip/render',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/analyze/$clipId': typeof AnalyzeClipIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/puzzle/$date': typeof PuzzleDateRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/puzzle/': typeof PuzzleIndexRoute
  '/api/clip/render': typeof ApiClipRenderRoute
  '/api/clip/sign': typeof ApiClipSignRoute
  '/forum/c/$slug': typeof ForumCSlugRoute
  '/forum/t/$id': typeof ForumTIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/analyze/$clipId': typeof AnalyzeClipIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/puzzle/$date': typeof PuzzleDateRoute
  '/blog': typeof BlogIndexRoute
  '/forum': typeof ForumIndexRoute
  '/puzzle': typeof PuzzleIndexRoute
  '/api/clip/render': typeof ApiClipRenderRoute
  '/api/clip/sign': typeof ApiClipSignRoute
  '/forum/c/$slug': typeof ForumCSlugRoute
  '/forum/t/$id': typeof ForumTIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/analyze/$clipId': typeof AnalyzeClipIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/puzzle/$date': typeof PuzzleDateRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/puzzle/': typeof PuzzleIndexRoute
  '/api/clip/render': typeof ApiClipRenderRoute
  '/api/clip/sign': typeof ApiClipSignRoute
  '/forum/c/$slug': typeof ForumCSlugRoute
  '/forum/t/$id': typeof ForumTIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/game'
    | '/history'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/analyze/$clipId'
    | '/blog/$slug'
    | '/player/$playerId'
    | '/puzzle/$date'
    | '/blog/'
    | '/forum/'
    | '/puzzle/'
    | '/api/clip/render'
    | '/api/clip/sign'
    | '/forum/c/$slug'
    | '/forum/t/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/game'
    | '/history'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/analyze/$clipId'
    | '/blog/$slug'
    | '/player/$playerId'
    | '/puzzle/$date'
    | '/blog'
    | '/forum'
    | '/puzzle'
    | '/api/clip/render'
    | '/api/clip/sign'
    | '/forum/c/$slug'
    | '/forum/t/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/game'
    | '/history'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/analyze/$clipId'
    | '/blog/$slug'
    | '/player/$playerId'
    | '/puzzle/$date'
    | '/blog/'
    | '/forum/'
    | '/puzzle/'
    | '/api/clip/render'
    | '/api/clip/sign'
    | '/forum/c/$slug'
    | '/forum/t/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  ClipsRoute: typeof ClipsRoute
  FriendsRoute: typeof FriendsRoute
  GameRoute: typeof GameRoute
  HistoryRoute: typeof HistoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  AnalyzeClipIdRoute: typeof AnalyzeClipIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  PuzzleDateRoute: typeof PuzzleDateRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  PuzzleIndexRoute: typeof PuzzleIndexRoute
  ApiClipRenderRoute: typeof ApiClipRenderRoute
  ApiClipSignRoute: typeof ApiClipSignRoute
  ForumCSlugRoute: typeof ForumCSlugRoute
  ForumTIdRoute: typeof ForumTIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/': {
      id: '/puzzle/'
      path: '/puzzle'
      fullPath: '/puzzle/'
      preLoaderRoute: typeof PuzzleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$date': {
      id: '/puzzle/$date'
      path: '/puzzle/$date'
      fullPath: '/puzzle/$date'
      preLoaderRoute: typeof PuzzleDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$clipId': {
      id: '/analyze/$clipId'
      path: '/analyze/$clipId'
      fullPath: '/analyze/$clipId'
      preLoaderRoute: typeof AnalyzeClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/t/$id': {
      id: '/forum/t/$id'
      path: '/forum/t/$id'
      fullPath: '/forum/t/$id'
      preLoaderRoute: typeof ForumTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/c/$slug': {
      id: '/forum/c/$slug'
      path: '/forum/c/$slug'
      fullPath: '/forum/c/$slug'
      preLoaderRoute: typeof ForumCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clip/sign': {
      id: '/api/clip/sign'
      path: '/api/clip/sign'
      fullPath: '/api/clip/sign'
      preLoaderRoute: typeof ApiClipSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clip/render': {
      id: '/api/clip/render'
      path: '/api/clip/render'
      fullPath: '/api/clip/render'
      preLoaderRoute: typeof ApiClipRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  ClipsRoute: ClipsRoute,
  FriendsRoute: FriendsRoute,
  GameRoute: GameRoute,
  HistoryRoute: HistoryRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  AnalyzeClipIdRoute: AnalyzeClipIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  PuzzleDateRoute: PuzzleDateRoute,
  BlogIndexRoute: BlogIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  PuzzleIndexRoute: PuzzleIndexRoute,
  ApiClipRenderRoute: ApiClipRenderRoute,
  ApiClipSignRoute: ApiClipSignRoute,
  ForumCSlugRoute: ForumCSlugRoute,
  ForumTIdRoute: ForumTIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
