/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PuzzleRouteImport } from './routes/puzzle'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzleDateRouteImport } from './routes/puzzle.$date'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleRoute = PuzzleRouteImport.update({
  id: '/puzzle',
  path: '/puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleDateRoute = PuzzleDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => PuzzleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/puzzle': typeof PuzzleRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/puzzle/$date': typeof PuzzleDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/puzzle': typeof PuzzleRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/puzzle/$date': typeof PuzzleDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clips': typeof ClipsRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/puzzle': typeof PuzzleRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/puzzle/$date': typeof PuzzleDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/history'
    | '/onboarding'
    | '/puzzle'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/puzzle/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/history'
    | '/onboarding'
    | '/puzzle'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/puzzle/$date'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/clips'
    | '/friends'
    | '/history'
    | '/onboarding'
    | '/puzzle'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/puzzle/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClipsRoute: typeof ClipsRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PuzzleRoute: typeof PuzzleRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle': {
      id: '/puzzle'
      path: '/puzzle'
      fullPath: '/puzzle'
      preLoaderRoute: typeof PuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$date': {
      id: '/puzzle/$date'
      path: '/$date'
      fullPath: '/puzzle/$date'
      preLoaderRoute: typeof PuzzleDateRouteImport
      parentRoute: typeof PuzzleRoute
    }
  }
}

interface PuzzleRouteChildren {
  PuzzleDateRoute: typeof PuzzleDateRoute
}

const PuzzleRouteChildren: PuzzleRouteChildren = {
  PuzzleDateRoute: PuzzleDateRoute,
}

const PuzzleRouteWithChildren =
  PuzzleRoute._addFileChildren(PuzzleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClipsRoute: ClipsRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  OnboardingRoute: OnboardingRoute,
  PuzzleRoute: PuzzleRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
